<?php
/**
 * Created by PhpStorm.
 * User: SimplyWorld
 * Date: 03.05.2017
 * Time: 13:13
 */

namespace app\modules\admin\controllers;

use yii\web\Controller;

class AppAdminController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}